### PR TITLE
fix: add error logs to s3_client #963

### PR DESCRIPTION
**Pull request by ClaireMao1996**
Related to https://github.com/samatechtw/pubstudio/issues/963

### CODE REVIEW

**Comment by ClaireMao1996** [comment]
It seems that the backups were not successfully uploaded to S3, but the current error message is not clear enough. 
In this PR I added some logs to better observe the actual error.

截圖 2024-01-19 下午4 35 21

**Comment by sampullman** [comment]
Got it, thanks! It's probably some environment or cloudflare configuration error.

**Comment by ClaireMao1996** [comment]
The signature doesn't match!

截圖 2024-01-21 中午12 31 54

Maybe the access key that we provided in `s3_client.rs` is wrong?

**Comment by sampullman** [comment]
The environment variable wasn't provided correctly in the CI build. I confirmed that the env is correct now, but I don't see a backup in R2 yet. I haven't had a chance to check if there are any more error logs.

**Comment by ClaireMao1996** [comment]
Sorry, I didn't notice that you had already fixed it. I'll check it right now!

**Pull request merged**
