### PR TITLE
fix: update_key date format incompatible #200

### LINKED ISSUE #200: update_key date format incompatible
See discussion starting here: https://github.com/samatechtw/pubstudio-builder/pull/199#issuecomment-1876247014

### PR DESCRIPTION
**Pull request by ClaireMao1996**
Close #200

### CODE REVIEW

**Comment by sampullman** [comment]
👌

**Comment by ClaireMao1996** [comment]
Oh no, the same issue still exists on stg.
I didn't encounter any problems during local testing🤔. I'll take another look at this issue tomorrow

**Comment by sampullman** [comment]
I see! I'll double check later to make sure the stg pods were updated as expected.

**Comment by sampullman** [comment]
I found the problem, it turns out the stg site server was not receiving updates, since I forgot to update the image location after splitting the repositories. Since we haven't made many updates recently, I didn't notice before! It should be working now, I'll make sure Watchtower pulls the image correctly next time.

**Pull request merged**
